### ISSUE TITLE
Cannot read property addListener of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/scenery-phet#658]
```
scenery-phet : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611216481154/scenery-phet/scenery-phet_en.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611216481154%22%2C%22timestamp%22%3A1611219806781%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'addListener' of undefined
TypeError: Cannot read property 'addListener' of undefined
at new GrabDragInteraction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611216481154/scenery-phet/js/accessibility/GrabDragInteraction.js:428:38)
at Object.createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611216481154/scenery-phet/js/demo/ComponentsScreenView.js:1464:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611216481154/sun/js/demo/DemosScreenView.js:129:26
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611216481154/axon/js/TinyEmitter.js:71:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611216481154/axon/js/Property.js:280:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611216481154/axon/js/Property.js:178:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611216481154/axon/js/Property.js:350:32)
at ComboBoxListBox.Action.parameters.phetioPrivate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611216481154/sun/js/ComboBoxListBox.js:72:22)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611216481154/axon/js/Action.js:225:18)
at Object.up (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611216481154/sun/js/ComboBoxListBox.js:92:20)
id: Bayes Chrome
Snapshot from 1/21/2021, 1:08:01 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - usage was overlooked after an API change. Fixed above.
