### ISSUE TITLE
Create sound for the back button

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/scenery-phet#677]
It was brought to my attention that we do not have a sound for the back button (ex. In Fourier). [Here are a few for us to try out.](https://drive.google.com/drive/folders/1AMcw551h-SWgyf_h-clYD_-5i0Jvehjv?usp=sharing)

- back-button-003.mp3
- back-button-002.mp3
- back-button-001.mp3

**Comment by jbphet** [comment]
I'm transferring this issue from the vegas repo to scenery-phet, since that's where the back button lives nowadays.

**Comment by jbphet** [comment]
We reviewed these three sounds in the vegas demo and in fourier-making-waves in today's sound design meeting and decided that we'll wait until the button selection sounds are in place before making any decisions.

**Comment by jbphet** [comment]
I've marked this as blocking publication.  This only applies to sims that use this button, or that use other components that use this button.  This is because there will be untested code in the back button for a while as we work to determine what sound to use for it.

**Comment by jbphet** [comment]
@Ashton-Morris, @emily-phet, and @arouinfar - I've published a dev version of the vegas demo that includes an "Options" dialog that allows us to choose between different sounds for the back button, and I've integrated the trhee initial candidate sounds that @Ashton-Morris provided (see above). Please give it a try and log your feedback in this ticket. The dev version can be found at https://phet-dev.colorado.edu/html/vegas/1.0.0-dev.5/phet/vegas_en_phet.html. The back button can be found on the 3rd screen of the demo.

**Comment by KatieWoe** [comment]
CT error seems to be showing up related to this:
```
scenery-phet : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/scenery-phet_en.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623077853363%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'soundIndexForBackButtonProperty' of undefined
TypeError: Cannot read property 'soundIndexForBackButtonProperty' of undefined
at Object.play (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/js/buttons/BackButton.js:42:61)
at playSound (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/sun/js/buttons/RectangularPushButton.js:54:51)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Emitter.js:64:19)
at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/sun/js/buttons/PushButtonModel.js:93:36)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Property.js:271:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Property.js:186:14)
id: Bayes Chrome
Snapshot from 6/7/2021, 8:37:15 AM

----------------------------------

scenery-phet : interactive-description-fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078139024%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: Cannot read property 'soundIndexForBackButtonProperty' of undefined
TypeError: Cannot read property 'soundIndexForBackButtonProperty' of undefined
at Object.play (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078139024%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:979:1022066)
at r (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078139024%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:979:880339)
at a.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078139024%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:979:42669)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078139024%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:979:412542
at La.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078139024%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:979:411888)
at La.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078139024%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:979:412718)
at e (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078139024%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:979:869936)
at Xt.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078139024%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:979:42669)
at se._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078139024%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:979:76687)
at set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078139024%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:979:76101)
id: Bayes Chrome
Snapshot from 6/7/2021, 8:37:15 AM

----------------------------------

scenery-phet : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/scenery-phet_en.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623077695273%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: Cannot read property 'soundIndexForBackButtonProperty' of undefined
TypeError: Cannot read property 'soundIndexForBackButtonProperty' of undefined
at Object.play (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/js/buttons/BackButton.js:42:61)
at playSound (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/sun/js/buttons/RectangularPushButton.js:54:51)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Emitter.js:64:19)
at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/sun/js/buttons/PushButtonModel.js:93:36)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Property.js:271:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Property.js:186:14)
id: Bayes Chrome
Snapshot from 6/7/2021, 8:37:15 AM

----------------------------------

scenery-phet : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623079459463%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: Cannot read property 'soundIndexForBackButtonProperty' of undefined
TypeError: Cannot read property 'soundIndexForBackButtonProperty' of undefined
at Object.play (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623079459463%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:979:1022066)
at r (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623079459463%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:979:880339)
at a.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623079459463%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:979:42669)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623079459463%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:979:412542
at La.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623079459463%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:979:411888)
at La.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623079459463%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:979:412718)
at e (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623079459463%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:979:869936)
at Xt.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623079459463%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:979:42669)
at se._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623079459463%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:979:76687)
at set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623079459463%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:979:76101)
id: Bayes Chrome
Snapshot from 6/7/2021, 8:37:15 AM

----------------------------------

scenery-phet : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/scenery-phet_en.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1623076635488%22%2C%22timestamp%22%3A1623078414466%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read property 'soundIndexForBackButtonProperty' of undefined
TypeError: Cannot read property 'soundIndexForBackButtonProperty' of undefined
at Object.play (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/scenery-phet/js/buttons/BackButton.js:42:61)
at playSound (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/sun/js/buttons/RectangularPushButton.js:54:51)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Emitter.js:64:19)
at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/sun/js/buttons/PushButtonModel.js:93:36)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Property.js:271:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623076635488/axon/js/Property.js:186:14)
id: Bayes Chrome
Snapshot from 6/7/2021, 8:37:15 AM
```

**Comment by samreid** [comment]
This one seems related to https://github.com/phetsims/vegas/issues/89.  At today's phet-io meeting, we were wondering what additional steps need to be done to unblock publication.  @jbphet can you please take a look?

**Comment by samreid** [comment]
@pixelzoom suggested that since Gravity and Orbits doesn't have a back button or game, it may not be blocked by this issue.

**Comment by samreid** [comment]
@pixelzoom also said Natural Selection is also not impacted by this.

**Comment by pixelzoom** [comment]
I was not aware of this issue, and did not move any of this work to the vegas "sound-design" work as part of phetsims/vegas#89.

**Comment by jbphet** [comment]
I fixed the issue that was causing CT failures.  I had neglected to handle the case where the global variable that is supposed to be set by an options dialog is not defined because the options dialog was not present.  My bad.

I'm going to mark this as blocking publication again, but _this only applies to sims that have sound enabled and use the back button!_  All other sims should be unaffected.

**Comment by pixelzoom** [comment]
FYI, Fourier "feature complete" milestone has been moved to 8/24/21.

**Comment by jbphet** [comment]
@Ashton-Morris is going to supply one or two alternatives based on the discussion that he and @emily-phet had on this last week.

**Comment by Ashton-Morris** [comment]
I have a few alternatives for us to listen to at our n[ext meeting.](https://drive.google.com/drive/folders/1AMcw551h-SWgyf_h-clYD_-5i0Jvehjv?usp=sharing)

- back-button-006.mp3
- back-button-005.mp3
- back-button-004.mp3
- back-button-007.mp3

**Comment by jbphet** [comment]
We reviewed this in today's sound design meeting and decided upon back-button-006.  The next steps are to remove all unused sounds and finalize the sound files.

**Comment by jbphet** [comment]
@Ashton-Morris - I need three things from you to help finish this off:

- [ ] I'll need a .wav version of the back-button-006 sound for the assets folder
- [ ] Please review the current volume level for this button in the vegas demo on master and let me know if you approve.  I ended up at a lower output level for this one versus, say, the reset-all sound.  I'm not entirely sure why, but this it what sounded about right to me using headphones.  It may be because it has more length and frequencies than the reset-all sound.  At any rate, I'd like your input on this level.
- [ ] I've changed the name of the sound in the code base from `back-button-006` to `go-back`, so please update your own tracking system for this sound.

Please assign this back to me when you're done with the items above.

**Comment by jbphet** [comment]
We reviewed and adjusted the level for this button during today's sound design meeting, so I checked off one of the items above.

**Comment by Ashton-Morris** [comment]
- [go-back.wav](https://drive.google.com/file/d/1t4JcgdAZyw8HCTxxPMhS7ob5L2eqJoe2/view?usp=sharing)

**Comment by zepumph** [comment]
@jbphet said this is no longer blocking during today's dev meeting.

**Comment by jbphet** [comment]
@Ashton-Morris - The sound you linked to above isn't normalized to our -1 dBFS standard.  Can you please update it to this level and assign back to me again when it's ready?

**Comment by Ashton-Morris** [comment]
[Updated Version Here](https://drive.google.com/file/d/1t4JcgdAZyw8HCTxxPMhS7ob5L2eqJoe2/view?usp=sharing)

**Comment by jbphet** [comment]
Asset added, I think we're done here.  Closing.

**Comment by pixelzoom** [comment]
It looks like the Back button sound was completed in https://github.com/phetsims/scenery-phet/issues/677. Do we now have support for all of the vegas components used by Fourier? 

If so... @jbphet please review in Fourier (master), then assign to @arouinfar for sign-off.  Reviewing will be easier if you run with `?showAnwers&showReward`, which will show the challenge answers, and show the reward dialog after every correct answer. See https://github.com/phetsims/special-ops/blob/master/doc/phetTeamMember.md for how to enabled `showAnswers`.
