### ISSUE TITLE
CT: FlowConstraint assertion failures

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#722]
CT is reporting 2 different failures in FlowConstraint.js:

```
scenery-phet : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643729262081/scenery-phet/scenery-phet_en.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643729262081%22%2C%22timestamp%22%3A1643731431926%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Will not be able to fit in this preferred size
Error: Assertion failed: Will not be able to fit in this preferred size
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643729262081/assert/js/assert.js:25:13)
at FlowConstraint.layout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643729262081/chipper/dist/js/scenery/js/layout/FlowConstraint.js:175:15)
at FlowConstraint.updateLayout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643729262081/chipper/dist/js/scenery/js/layout/LayoutConstraint.js:92:14)
at FlowConstraint.updateLayoutAutomatically (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643729262081/chipper/dist/js/scenery/js/layout/LayoutConstraint.js:106:12)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643729262081/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at TinyProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643729262081/chipper/dist/js/axon/js/TinyProperty.js:122:10)
at TinyProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643729262081/chipper/dist/js/axon/js/TinyProperty.js:58:12)
at TinyProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643729262081/chipper/dist/js/axon/js/TinyProperty.js:67:10)
at FlowBox.set preferredWidth [as preferredWidth] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643729262081/chipper/dist/js/scenery/js/layout/WidthSizable.js:28:41)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643729262081/chipper/dist/js/scenery-phet/js/demo/ComponentsScreenView.js:1013:30
id: Bayes Chrome
Snapshot from 2/1/2022, 8:27:42 AM
```

```
scenery-phet : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643711167223/scenery-phet/scenery-phet_en.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643711167223%22%2C%22timestamp%22%3A1643715325413%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643711167223/assert/js/assert.js:25:13)
at FlowConstraint.set orientation [as orientation] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643711167223/chipper/dist/js/scenery/js/layout/FlowConfigurable.js:147:17)
at FlowBox.set orientation [as orientation] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643711167223/chipper/dist/js/scenery/js/layout/FlowBox.js:155:34)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643711167223/chipper/dist/js/scenery/js/nodes/Node.js:6019:21
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643711167223/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643711167223/sherpa/lib/lodash-4.17.4.js:9359:14)
at FlowBox.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643711167223/chipper/dist/js/scenery/js/nodes/Node.js:6006:7)
at new FlowBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643711167223/chipper/dist/js/scenery/js/layout/FlowBox.js:44:10)
at Object.demoFlowBox [as createNode] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643711167223/chipper/dist/js/scenery-phet/js/demo/ComponentsScreenView.js:1220:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643711167223/chipper/dist/js/sun/js/demo/DemosScreenView.js:116:26
id: Bayes Chrome
Snapshot from 2/1/2022, 3:26:07 AM
```

**Comment by jonathanolson** [comment]
Thanks, looking into it (working on related logic right now).

**Comment by pixelzoom** [comment]
No progress noted since Feb 1.  @kathy-phet please prioritize.

**Comment by jonathanolson** [comment]
I don't see this happening in CT, and fuzzing for 30min didn't show this.

**Comment by marlitas** [comment]
I also am not seeing this in CT anymore. Closing. Please feel free to reopen if this comes up again.
