### ISSUE TITLE
CT Cannot read properties of undefined (reading 'padRatio')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/scenery-phet#738]
```
scenery-phet : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192590112%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'padRatio')
TypeError: Cannot read properties of undefined (reading 'padRatio')
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192590112%7D&fuzz&memoryLimit=1000:1013:773979)
at Array.forEach
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192590112%7D&fuzz&memoryLimit=1000:1013:773793)
at Array.forEach
at Xu.layout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192590112%7D&fuzz&memoryLimit=1000:1013:773722)
at Xu.updateLayout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192590112%7D&fuzz&memoryLimit=1000:1013:759950)
at Xu.updateLayoutAutomatically (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192590112%7D&fuzz&memoryLimit=1000:1013:760059)
at Zu.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192590112%7D&fuzz&memoryLimit=1000:1013:777741)
at Zu.set children [as children] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192590112%7D&fuzz&memoryLimit=1000:1013:393226)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192590112%7D&fuzz&memoryLimit=1000:1013:427541)
id: Bayes Chrome
Snapshot from 5/10/2022, 5:29:52 AM

----------------------------------

scenery-phet : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/scenery-phet_en.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652185203492%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: align stretch not supported, with the orientation HORIZONTAL, the valid values are top,bottom,center,origin,
Error: Assertion failed: align stretch not supported, with the orientation HORIZONTAL, the valid values are top,bottom,center,origin,
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/assert/js/assert.js:28:13)
at assert (FlowConfigurable.ts:255:16)
at (FlowBox.ts:216:4)
at (Node.ts:5994:10)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/sherpa/lib/lodash-4.17.4.js:9359:14)
at each (Node.ts:5977:6)
at mutate (FlowBox.ts:65:9)
at (ComponentsScreenView.js:1138:20)
at Array.forEach
id: Bayes Chrome
Snapshot from 5/10/2022, 5:29:52 AM

----------------------------------

scenery-phet : interactive-description-fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192809681%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'padRatio')
TypeError: Cannot read properties of undefined (reading 'padRatio')
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192809681%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1013:773979)
at Array.forEach
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192809681%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1013:773793)
at Array.forEach
at Xu.layout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192809681%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1013:773722)
at Xu.updateLayout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192809681%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1013:759950)
at Xu.updateLayoutAutomatically (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192809681%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1013:760059)
at Zu.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192809681%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1013:777741)
at Zu.set children [as children] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192809681%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1013:393226)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652182192012/scenery-phet/build/phet/scenery-phet_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652182192012%22%2C%22timestamp%22%3A1652192809681%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1013:427541)
id: Bayes Chrome
Snapshot from 5/10/2022, 5:29:52 AM
```

**Comment by zepumph** [comment]
I'm not too sure about this one, over to the responsible dev for scenery-phet.

**Comment by jonathanolson** [comment]
This was my fault, likely fix committed above.

**Comment by KatieWoe** [comment]
Looks ok on CT. Closing
