### ISSUE TITLE
Create a Clapperboard for synchronizing recording

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#739]
In https://github.com/phetsims/ratio-and-proportion/issues/468 and for Quad as well, there is upcoming research being done. In these studies, recording will be done with audio, video camera, screen capture, and PhET-iO data stream. We want to create a way to synchronize all of these within the sim, and during a meeting today, @BLFiedler @jessegreenberg and I came up with some sort of idea for a "clapperboard" like they have in the movies. This will have a sound, visual cue, and be instrumented so that it emits to the data stream.

**Comment by jessegreenberg** [comment]
In the above commit I made a first pass at adding Tandems to the button, it is probably incomplete but it allows some use in studio.

**Comment by zepumph** [comment]
Great thanks! I also needed to pass it through in RAP. Now you get this data stream event when you press the button


```
{
  "index": 153,
  "time": 1652379974013,
  "type": "user",
  "phetioID": "ratioAndProportion.general.controller.input.mouseUpAction",
  "name": "executed",
  "componentType": "PhetioActionIO<Vector2IO, EventIO>",
  "data": {
    "point": {
      "x": 329,
      "y": 172
    },
    "event": {
      "constructorName": "PointerEvent",
      "altKey": false,
      "button": 0,
      "charCode": null,
      "clientX": 329,
      "clientY": 172,
      "code": null,
      "ctrlKey": false,
      "deltaMode": null,
      "deltaX": null,
      "deltaY": null,
      "deltaZ": null,
      "key": null,
      "keyCode": null,
      "metaKey": false,
      "pageX": 329,
      "pageY": 172,
      "pointerId": 1,
      "pointerType": "mouse",
      "scale": null,
      "shiftKey": false,
      "target": {},
      "type": "pointerup",
      "relatedTarget": null,
      "which": 1
    }
  },
  "metadata": {
    "dataKeys": [
      "point",
      "event"
    ],
    "playback": true
  },
  "children": [
    {
      "index": 154,
      "time": 1652379974013,
      "type": "user",
      "phetioID": "ratioAndProportion.global.view.clapperboardButton.synchronizeButton.pressListener.releaseAction",
      "name": "executed",
      "componentType": "PhetioActionIO<NullableIO<SceneryEventIO>>",
      "data": {
        "event": {
          "type": "up",
          "domEventType": {
            "constructorName": "PointerEvent",
            "altKey": false,
            "button": 0,
            "charCode": null,
            "clientX": 329,
            "clientY": 172,
            "code": null,
            "ctrlKey": false,
            "deltaMode": null,
            "deltaX": null,
            "deltaY": null,
            "deltaZ": null,
            "key": null,
            "keyCode": null,
            "metaKey": false,
            "pageX": 329,
            "pageY": 172,
            "pointerId": 1,
            "pointerType": "mouse",
            "scale": null,
            "shiftKey": false,
            "target": {},
            "type": "pointerup",
            "relatedTarget": null,
            "which": 1
          },
          "point": {
            "x": 329,
            "y": 172
          }
        }
      },
      "children": [
        {
          "index": 155,
          "time": 1652379974013,
          "type": "user",
          "phetioID": "ratioAndProportion.global.view.clapperboardButton.synchronizeButton.firedEmitter",
          "name": "emitted",
          "componentType": "EmitterIO<>"
        },
        {
          "index": 156,
          "time": 1652379974014,
          "type": "user",
          "phetioID": "ratioAndProportion.global.view.clapperboardButton.synchronizeButton.pressListener.releaseAction.executedEmitter",
          "name": "emitted",
          "componentType": "EmitterIO<NullableIO<SceneryEventIO>>",
          "data": {
            "event": {
              "type": "up",
              "domEventType": {
                "constructorName": "PointerEvent",
                "altKey": false,
                "button": 0,
                "charCode": null,
                "clientX": 329,
                "clientY": 172,
                "code": null,
                "ctrlKey": false,
                "deltaMode": null,
                "deltaX": null,
                "deltaY": null,
                "deltaZ": null,
                "key": null,
                "keyCode": null,
                "metaKey": false,
                "pageX": 329,
                "pageY": 172,
                "pointerId": 1,
                "pointerType": "mouse",
                "scale": null,
                "shiftKey": false,
                "target": {},
                "type": "pointerup",
                "relatedTarget": null,
                "which": 1
              },
              "point": {
                "x": 329,
                "y": 172
              }
            }
          }
        }
      ]
    },
    {
      "index": 157,
      "time": 1652379974014,
      "type": "user",
      "phetioID": "ratioAndProportion.general.controller.input.mouseUpAction.executedEmitter",
      "name": "emitted",
      "componentType": "EmitterIO<Vector2IO, EventIO>",
      "data": {
        "point": {
          "x": 329,
          "y": 172
        },
        "event": {
          "constructorName": "PointerEvent",
          "altKey": false,
          "button": 0,
          "charCode": null,
          "clientX": 329,
          "clientY": 172,
          "code": null,
          "ctrlKey": false,
          "deltaMode": null,
          "deltaX": null,
          "deltaY": null,
          "deltaZ": null,
          "key": null,
          "keyCode": null,
          "metaKey": false,
          "pageX": 329,
          "pageY": 172,
          "pointerId": 1,
          "pointerType": "mouse",
          "scale": null,
          "shiftKey": false,
          "target": {},
          "type": "pointerup",
          "relatedTarget": null,
          "which": 1
        }
      }
    }
  ]
}

```

**Comment by zepumph** [comment]
@BLFiedler please let us know if there is anything else you want changed about this button. You can test it out in Ratio and Proportion on master.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/quadrilateral/issues/153 It was discovered that the button could be pressed multiple times with an attempt to add the `visualNode` as a child multiple times. Potential fix in the above commit.

**Comment by zepumph** [comment]
I see. Yes thanks that makes sense.

**Comment by zepumph** [comment]
Since your commit I've been getting an error like:

```
ratio-and-proportion : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652884467426/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652884467426%22%2C%22timestamp%22%3A1652886128953%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: alignBounds should be a non-empty finite Bounds2
Error: Assertion failed: alignBounds should be a non-empty finite Bounds2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652884467426/assert/js/assert.js:28:13)
at assert (AlignBox.ts:203:14)
at setAlignBounds (AlignBox.ts:222:50)
at (AlignGroup.ts:292:4)
at setBoxBounds (AlignGroup.ts:255:13)
at updateLayout (AlignGroup.ts:300:9)
at onAlignBoxResized (AlignBox.ts:186:18)
at listener (TinyEmitter.ts:93:8)
at emit (TinyStaticProperty.ts:58:9)
at notifyListeners (Node.ts:1480:30)
id: Bayes Chrome
Snapshot from 5/18/2022, 8:34:27 AM
```

On CT. I think it is because there is no actual content anymore in the Node. So I instead set enabled instead of visible on the button. I'll see if it clears up CT.

**Comment by zepumph** [comment]
@BLFiedler is 1 second a good amount of time to have the video icon up? Anything else for this issue from you side?

**Comment by BLFiedler** [comment]
Could we try a tone that is a bit more discrete in the on/off? The sound profile of this one feels like it may have a bit of a fade, which may make it more difficult to place the start and stop. It is okay if it is not pleasant! It just needs to be heard!

**Comment by jessegreenberg** [comment]
This came up during Quad meetings today and it was discussed that the character of the PitchedPopSoundGenerator could make it difficult to find the sound event in the recording. I tried increasing the duration but it still had too much swoop. @BLFiedler suggested using a simple waveform instead like a censor beep.

**Comment by jessegreenberg** [comment]
I hope you don't mind @zepumph, I went ahead and swapped out the PitchedPopSoundGenerator for a OscillatorSoundGenerator. It was confirmed as OK during quadrilateral meetings today.

What does that leave for this issue? There are a couple of TODOs about PhET-iO instrumentation. In quadrilateral I have been using the button's `pressListener.releaseAction` to find when it is pressed in the data stream.

**Comment by zepumph** [comment]
@jessegreenberg should we delete this type, or keep it unused in scenery-phet for next research study? Please close.
