### ISSUE TITLE
CT align stretch not supported, the valid values are left,right,center,origin or null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/scenery-phet#741]
May be related to https://github.com/phetsims/scenery-phet/issues/738
```
scenery-phet : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/scenery-phet/scenery-phet_en.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652860074542%22%2C%22timestamp%22%3A1652861319609%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: align stretch not supported, the valid values are left,right,center,origin or null
Error: Assertion failed: align stretch not supported, the valid values are left,right,center,origin or null
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/assert/js/assert.js:28:13)
at assert (GridConfigurable.ts:164:16)
at (mutate.js:43:6)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/sherpa/lib/lodash-4.17.4.js:9359:14)
at each (mutate.js:37:4)
at mutate (GridConfigurable.ts:111:6)
at mutateConfigurable (GridCell.ts:116:9)
at setOptions (GridCell.ts:51:9)
at (GridBox.ts:284:17)
id: Bayes Chrome
Snapshot from 5/18/2022, 1:47:54 AM

----------------------------------

scenery-phet : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/scenery-phet/scenery-phet_en.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652860074542%22%2C%22timestamp%22%3A1652871605301%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: align stretch not supported, the valid values are left,right,center,origin or null
Error: Assertion failed: align stretch not supported, the valid values are left,right,center,origin or null
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/assert/js/assert.js:28:13)
at assert (GridConfigurable.ts:164:16)
at (mutate.js:43:6)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/sherpa/lib/lodash-4.17.4.js:9359:14)
at each (mutate.js:37:4)
at mutate (GridConfigurable.ts:111:6)
at mutateConfigurable (GridCell.ts:116:9)
at setOptions (GridCell.ts:51:9)
at (GridBox.ts:284:17)
id: Bayes Chrome
Snapshot from 5/18/2022, 1:47:54 AM

----------------------------------

scenery-phet : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/scenery-phet/scenery-phet_en.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652860074542%22%2C%22timestamp%22%3A1652862846581%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: align stretch not supported, the valid values are left,right,center,origin or null
Error: Assertion failed: align stretch not supported, the valid values are left,right,center,origin or null
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/assert/js/assert.js:28:13)
at assert (GridConfigurable.ts:164:16)
at (mutate.js:43:6)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652860074542/sherpa/lib/lodash-4.17.4.js:9359:14)
at each (mutate.js:37:4)
at mutate (GridConfigurable.ts:111:6)
at mutateConfigurable (GridCell.ts:116:9)
at setOptions (GridCell.ts:51:9)
at (GridBox.ts:284:17)
id: Bayes Chrome
Snapshot from 5/18/2022, 1:47:54 AM
```

**Comment by jonathanolson** [comment]
I believe the commit above should fix this.

**Comment by KatieWoe** [comment]
I will reopen if it shows up again
