### ISSUE TITLE
CT Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/scenery-phet#765]
```
scenery-phet : top-level-unit-tests : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/scenery-phet/scenery-phet-tests.html
5 out of 6 tests passed. 1 failed.
GrabDragInteraction: GrabDragInteraction defaults failed:
Died on test #2 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery-phet/js/accessibility/GrabDragInteractionTests.js:15:7: Cannot read properties of undefined (reading 'value')
TypeError: Cannot read properties of undefined (reading 'value')
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/ReadOnlyProperty.js:157:98)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/Property.js:52:11)
at FlowConstraint.layout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/FlowConstraint.js:82:39)
at FlowConstraint.updateLayout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:182:14)
at FlowConstraint.updateLayoutAutomatically (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:196:12)
at FlowConstraint.set excludeInvisible [as excludeInvisible] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/NodeLayoutConstraint.js:59:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/phet-core/js/mutate.js:40:19
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/sherpa/lib/lodash-4.17.4.js:9359:14)
at mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/phet-core/js/mutate.js:35:5)

id: Bayes Puppeteer
Snapshot from 8/25/2022, 3:51:27 AM

----------------------------------

scenery-phet : top-level-unit-tests : unbuilt?brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/scenery-phet/scenery-phet-tests.html?brand=phet-io
5 out of 6 tests passed. 1 failed.
GrabDragInteraction: GrabDragInteraction defaults failed:
Died on test #2 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery-phet/js/accessibility/GrabDragInteractionTests.js:15:7: Cannot read properties of undefined (reading 'value')
TypeError: Cannot read properties of undefined (reading 'value')
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/ReadOnlyProperty.js:157:98)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/Property.js:52:11)
at FlowConstraint.layout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/FlowConstraint.js:82:39)
at FlowConstraint.updateLayout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:182:14)
at FlowConstraint.updateLayoutAutomatically (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:196:12)
at FlowConstraint.set excludeInvisible [as excludeInvisible] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/NodeLayoutConstraint.js:59:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/phet-core/js/mutate.js:40:19
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/sherpa/lib/lodash-4.17.4.js:9359:14)
at mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/phet-core/js/mutate.js:35:5)

id: Bayes Puppeteer
Snapshot from 8/25/2022, 3:51:27 AM

----------------------------------

scenery-phet : top-level-unit-tests : unbuilt?ea
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/scenery-phet/scenery-phet-tests.html?ea
5 out of 6 tests passed. 1 failed.
GrabDragInteraction: GrabDragInteraction defaults failed:
Died on test #2 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery-phet/js/accessibility/GrabDragInteractionTests.js:15:7: Cannot read properties of undefined (reading 'value')
TypeError: Cannot read properties of undefined (reading 'value')
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/ReadOnlyProperty.js:157:98)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/Property.js:52:11)
at FlowConstraint.layout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/FlowConstraint.js:82:39)
at FlowConstraint.updateLayout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:182:14)
at FlowConstraint.updateLayoutAutomatically (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:196:12)
at FlowConstraint.set excludeInvisible [as excludeInvisible] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/NodeLayoutConstraint.js:59:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/phet-core/js/mutate.js:40:19
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/sherpa/lib/lodash-4.17.4.js:9359:14)
at mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/phet-core/js/mutate.js:35:5)

id: Bayes Puppeteer
Snapshot from 8/25/2022, 3:51:27 AM

----------------------------------

scenery-phet : top-level-unit-tests : unbuilt?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/scenery-phet/scenery-phet-tests.html?ea&brand=phet-io
5 out of 6 tests passed. 1 failed.
GrabDragInteraction: GrabDragInteraction defaults failed:
Died on test #2 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery-phet/js/accessibility/GrabDragInteractionTests.js:15:7: Cannot read properties of undefined (reading 'value')
TypeError: Cannot read properties of undefined (reading 'value')
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/ReadOnlyProperty.js:157:98)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/Property.js:52:11)
at FlowConstraint.layout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/FlowConstraint.js:82:39)
at FlowConstraint.updateLayout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:182:14)
at FlowConstraint.updateLayoutAutomatically (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:196:12)
at FlowConstraint.set excludeInvisible [as excludeInvisible] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/scenery/js/layout/constraints/NodeLayoutConstraint.js:59:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/phet-core/js/mutate.js:40:19
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/sherpa/lib/lodash-4.17.4.js:9359:14)
at mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/phet-core/js/mutate.js:35:5)

id: Bayes Puppeteer
Snapshot from 8/25/2022, 3:51:27 AM
```

**Comment by samreid** [comment]
At today's dev meeting, @jessegreenberg volunteered to investigate.  Thanks!

**Comment by jessegreenberg** [comment]
This is no longer an issue on CT and I just confirmed that unit tests for scenery-phet are passing locally.
