### ISSUE TITLE
CT: required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/scenery-phet#776]
```
scenery-phet : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 57848ms
Building runnable repository (scenery-phet, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 12076ms
>> Unused mipmaps module: scenery-phet/mipmaps/lightBulbBase_png.js
>> Unused mipmaps module: scenery-phet/mipmaps/protractor_png.js
>> Unused string: key=WavelengthSlider.pattern_0wavelength_1units, value={0} {1}
>> Unused string: key=frequencyUnitsPattern, value={{frequency}} THz
>> Unused string: key=units_nm, value=nm
>> Unused string: key=key.k, value=K
>> Unused string: key=key.l, value=L
>> Unused string: key=webglWarning.ie11StencilBody, value=Update Internet Explorer by installing recommended Windows Update patches.
>> Unused string: key=keyboardHelpDialog.adjustSlider, value=Adjust slider
>> Unused string: key=keyboardHelpDialog.adjustInSmallerSteps, value=Adjust in smaller steps
>> Unused string: key=keyboardHelpDialog.adjustInLargerSteps, value=Adjust in larger steps
>> Unused string: key=keyboardHelpDialog.jumpToMinimum, value=Jump to minimum
>> Unused string: key=keyboardHelpDialog.jumpToMaximum, value=Jump to maximum
>> Unused string: key=keyboardHelpDialog.generalNavigation, value=General Navigation
>> Unused string: key=keyboardHelpDialog.moveToNextItem, value=Move to next item
>> Unused string: key=keyboardHelpDialog.moveToPreviousItem, value=Move to previous item
>> Unused string: key=keyboardHelpDialog.comboBox.chooseAThingPattern, value=Choose a {{thingTitle}}
>> Unused string: key=rulerCapitalized, value=Ruler
>> Unused string: key=ruler, value=Ruler
>> Unused string: key=zero, value=zero
>> Unused string: key=one, value=one
>> Unused string: key=two, value=two
>> Unused string: key=three, value=three
>> Unused string: key=four, value=four
>> Unused string: key=five, value=five
>> Unused string: key=six, value=six
>> Unused string: key=seven, value=seven
>> Unused string: key=eight, value=eight
>> Unused string: key=nine, value=nine
>> Unused string: key=ten, value=ten
>> Unused string: key=a11y.soundToggle.alert.simSoundOn, value=Sim sound on.
>> Unused string: key=a11y.soundToggle.alert.simSoundOff, value=Sim sound off.
>> Unused string: key=a11y.keyboardHelpDialog.general.tabDescription, value=Move to next item with Tab key.
>> Unused string: key=a11y.keyboardHelpDialog.general.shiftTabDescription, value=Move to previous item with Shift plus Tab key.
>> Unused string: key=a11y.stepButton.playingDescription, value=Pause sim to step forward little by little.
>> Unused string: key=a11y.stepButton.pausedDescription, value=Play sim to resume chosen speed.
>> Unused string: key=a11y.movementAlerter.down, value=down
>> Unused string: key=a11y.movementAlerter.left, value=left
>> Unused string: key=a11y.movementAlerter.right, value=right
>> Unused string: key=a11y.movementAlerter.up, value=up
>> Unused string: key=a11y.movementAlerter.upAndToTheRight, value=up and to the right
>> Unused string: key=a11y.movementAlerter.upAndToTheLeft, value=up and to the left
>> Unused string: key=a11y.movementAlerter.downAndToTheRight, value=down and to the right
>> Unused string: key=a11y.movementAlerter.downAndToTheLeft, value=down and to the left
>> Unused string: key=a11y.movementAlerter.leftBorderAlert, value=At left edge
>> Unused string: key=a11y.movementAlerter.rightBorderAlert, value=At right edge
>> Unused string: key=a11y.movementAlerter.topBorderAlert, value=At top
>> Unused string: key=a11y.movementAlerter.bottomBorderAlert, value=At bottom
>> Unused string: key=a11y.voicing.simSection.screenSummary.singleScreenIntroPattern, value={{sim}} is an interactive sim. It changes as you play with it.
>> Unused string: key=a11y.voicing.keyboardHelpDialog.general.descriptionPattern, value={{title}}. {{nextItem}} {{previousItem}} {{groupItem}} {{pressButtons}} {{exit}}
>> Unused string: key=a11y.voicing.grabDragHintPattern, value=Tap, hold, and drag to {{manipulation}}.
>> Unused string: key=a11y.voicing.grabbedAlert, value=Grabbed.
>> Unused string: key=a11y.voicing.draggableAlert, value=Draggable
>> Production minification complete: 103171ms (3251750 bytes)
>> Debug minification complete: 0ms (23477871 bytes)
Building brand: phet-io
>> Webpack build complete: 10133ms
>> Unused mipmaps module: scenery-phet/mipmaps/lightBulbBase_png.js
>> Unused mipmaps module: scenery-phet/mipmaps/protractor_png.js
>> Unused string: key=WavelengthSlider.pattern_0wavelength_1units, value={0} {1}
>> Unused string: key=frequencyUnitsPattern, value={{frequency}} THz
>> Unused string: key=units_nm, value=nm
>> Unused string: key=key.k, value=K
>> Unused string: key=key.l, value=L
>> Unused string: key=webglWarning.ie11StencilBody, value=Update Internet Explorer by installing recommended Windows Update patches.
>> Unused string: key=keyboardHelpDialog.adjustSlider, value=Adjust slider
>> Unused string: key=keyboardHelpDialog.adjustInSmallerSteps, value=Adjust in smaller steps
>> Unused string: key=keyboardHelpDialog.adjustInLargerSteps, value=Adjust in larger steps
>> Unused string: key=keyboardHelpDialog.jumpToMinimum, value=Jump to minimum
>> Unused string: key=keyboardHelpDialog.jumpToMaximum, value=Jump to maximum
>> Unused string: key=keyboardHelpDialog.generalNavigation, value=General Navigation
>> Unused string: key=keyboardHelpDialog.moveToNextItem, value=Move to next item
>> Unused string: key=keyboardHelpDialog.moveToPreviousItem, value=Move to previous item
>> Unused string: key=keyboardHelpDialog.comboBox.chooseAThingPattern, value=Choose a {{thingTitle}}
>> Unused string: key=rulerCapitalized, value=Ruler
>> Unused string: key=ruler, value=Ruler
>> Unused string: key=zero, value=zero
>> Unused string: key=one, value=one
>> Unused string: key=two, value=two
>> Unused string: key=three, value=three
>> Unused string: key=four, value=four
>> Unused string: key=five, value=five
>> Unused string: key=six, value=six
>> Unused string: key=seven, value=seven
>> Unused string: key=eight, value=eight
>> Unused string: key=nine, value=nine
>> Unused string: key=ten, value=ten
>> Unused string: key=a11y.soundToggle.alert.simSoundOn, value=Sim sound on.
>> Unused string: key=a11y.soundToggle.alert.simSoundOff, value=Sim sound off.
>> Unused string: key=a11y.keyboardHelpDialog.general.tabDescription, value=Move to next item with Tab key.
>> Unused string: key=a11y.keyboardHelpDialog.general.shiftTabDescription, value=Move to previous item with Shift plus Tab key.
>> Unused string: key=a11y.stepButton.playingDescription, value=Pause sim to step forward little by little.
>> Unused string: key=a11y.stepButton.pausedDescription, value=Play sim to resume chosen speed.
>> Unused string: key=a11y.movementAlerter.down, value=down
>> Unused string: key=a11y.movementAlerter.left, value=left
>> Unused string: key=a11y.movementAlerter.right, value=right
>> Unused string: key=a11y.movementAlerter.up, value=up
>> Unused string: key=a11y.movementAlerter.upAndToTheRight, value=up and to the right
>> Unused string: key=a11y.movementAlerter.upAndToTheLeft, value=up and to the left
>> Unused string: key=a11y.movementAlerter.downAndToTheRight, value=down and to the right
>> Unused string: key=a11y.movementAlerter.downAndToTheLeft, value=down and to the left
>> Unused string: key=a11y.movementAlerter.leftBorderAlert, value=At left edge
>> Unused string: key=a11y.movementAlerter.rightBorderAlert, value=At right edge
>> Unused string: key=a11y.movementAlerter.topBorderAlert, value=At top
>> Unused string: key=a11y.movementAlerter.bottomBorderAlert, value=At bottom
>> Unused string: key=a11y.voicing.simSection.screenSummary.singleScreenIntroPattern, value={{sim}} is an interactive sim. It changes as you play with it.
>> Unused string: key=a11y.voicing.keyboardHelpDialog.general.descriptionPattern, value={{title}}. {{nextItem}} {{previousItem}} {{groupItem}} {{pressButtons}} {{exit}}
>> Unused string: key=a11y.voicing.grabDragHintPattern, value=Tap, hold, and drag to {{manipulation}}.
>> Unused string: key=a11y.voicing.grabbedAlert, value=Grabbed.
>> Unused string: key=a11y.voicing.draggableAlert, value=Draggable
Fatal error: Perennial task failed:
Error: Unable to read "../scenery-phet/js/scenery-phet-phet-io-overrides.js" file (Error code: ENOENT).
at Object.util.error (/data/share/phet/continuous-testing/ct-snapshots/1665576408871/chipper/node_modules/grunt-legacy-util/index.js:55:39)
at Object.file.read (/data/share/phet/continuous-testing/ct-snapshots/1665576408871/chipper/node_modules/grunt/lib/grunt/file.js:224:22)
at /data/share/phet/continuous-testing/ct-snapshots/1665576408871/chipper/js/grunt/buildRunnable.js:193:69
at Array.map (<anonymous>)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1665576408871/chipper/js/grunt/buildRunnable.js:193:41)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1665576408871/chipper/js/grunt/Gruntfile.js:287:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1665576408871/chipper/js/grunt/Gruntfile.js:65:7)
Full Error details:
Error: Unable to read "../scenery-phet/js/scenery-phet-phet-io-overrides.js" file (Error code: ENOENT).
Snapshot from 10/12/2022, 6:06:48 AM

----------------------------------

scenery-phet : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/scenery-phet/scenery-phet_en.html?continuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665576408871%22%2C%22timestamp%22%3A1665580172986%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:214:16)
at initializePhetioObject (PhetioObject.ts:186:11)
at (ReadOnlyProperty.ts:156:4)
at (Property.ts:17:4)
at (BooleanProperty.ts:31:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:65:54)
at (ButtonModel.ts:106:4)
at (PushButtonModel.ts:71:4)
id: Bayes Puppeteer
Snapshot from 10/12/2022, 6:06:48 AM

----------------------------------

scenery-phet : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/phet-io-wrappers/state/?sim=scenery-phet&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22scenery-phet%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665576408871%22%2C%22timestamp%22%3A1665581546988%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:214:16)
at initializePhetioObject (PhetioObject.ts:186:11)
at (ReadOnlyProperty.ts:156:4)
at (Property.ts:17:4)
at (BooleanProperty.ts:31:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:65:54)
at (ButtonModel.ts:106:4)
at (PushButtonModel.ts:71:4)
id: Bayes Puppeteer
Snapshot from 10/12/2022, 6:06:48 AM

----------------------------------

scenery-phet : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/phet-io-wrappers/phet-io-wrappers-tests.html?sim=scenery-phet&phetioDebug=true&phetioWrapperDebug=true
32 out of 33 tests passed. 1 failed.
SimTests: scenery-phet: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/assert/js/assert.js:28:13)
at EnabledProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/tandem/js/PhetioObject.js:144:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/tandem/js/PhetioObject.js:117:12)
at new ReadOnlyProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/axon/js/ReadOnlyProperty.js:90:5)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/axon/js/Property.js:12:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/axon/js/BooleanProperty.js:20:5)
at new EnabledProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/axon/js/EnabledProperty.js:29:5)
at new EnabledComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/axon/js/EnabledComponent.js:31:55)
at new ButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/sun/js/buttons/ButtonModel.js:53:5)
at new PushButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/sun/js/buttons/PushButtonModel.js:32:5)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:214:16)
at initializePhetioObject (PhetioObject.ts:186:11)
at (ReadOnlyProperty.ts:156:4)
at (Property.ts:17:4)
at (BooleanProperty.ts:31:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:65:54)
at (ButtonModel.ts:106:4)
at (PushButtonModel.ts:71:4)
id: Bayes Puppeteer
Snapshot from 10/12/2022, 6:06:48 AM

----------------------------------

scenery-phet : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/phet-io-wrappers/phet-io-wrappers-tests.html?sim=scenery-phet
30 out of 31 tests passed. 1 failed.
SimTests: scenery-phet: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/assert/js/assert.js:28:13)
at EnabledProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/tandem/js/PhetioObject.js:144:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/tandem/js/PhetioObject.js:117:12)
at new ReadOnlyProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/axon/js/ReadOnlyProperty.js:90:5)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/axon/js/Property.js:12:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/axon/js/BooleanProperty.js:20:5)
at new EnabledProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/axon/js/EnabledProperty.js:29:5)
at new EnabledComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/axon/js/EnabledComponent.js:31:55)
at new ButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/sun/js/buttons/ButtonModel.js:53:5)
at new PushButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/chipper/dist/js/sun/js/buttons/PushButtonModel.js:32:5)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665576408871/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:214:16)
at initializePhetioObject (PhetioObject.ts:186:11)
at (ReadOnlyProperty.ts:156:4)
at (Property.ts:17:4)
at (BooleanProperty.ts:31:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:65:54)
at (ButtonModel.ts:106:4)
at (PushButtonModel.ts:71:4)
id: Bayes Puppeteer
Snapshot from 10/12/2022, 6:06:48 AM
```

**Comment by pixelzoom** [comment]
According to CT history, this problem started 10/12/2022, 7:15:15 AM.  It's been occurring on every CT cycle since then.  

The only commit I see to scenery-phet since then is by @zepumph in https://github.com/phetsims/scenery-phet/commit/775865131b92ea745689feabe7805c8cb01b4ce5.  So I'll start by assigning to him.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/commit/775865131b92ea745689feabe7805c8cb01b4ce5, it looks like @zepumph added phet-io features to package.json without running `grunt update`.

**Comment by zepumph** [comment]
While it does look like my commit broke it, `grunt update` shouldn't be picking up extra changes. Seems like it is from https://github.com/phetsims/scenery-phet/commit/62051ecb27f84d4f14e0a0764a605eeddf5eac39 over in https://github.com/phetsims/scenery-phet/issues/439

**Comment by zepumph** [comment]
adding validation: false did the trick
